
<!DOCTYPE html>
<html>

<Head>
    <title>College Dates</title>
    <script src="script.js"></script>
</Head>

<body>

    <h1>Welcome to College Dates!
    </h1>
    <p>College Dates is an app that will help match you with the right person for you based off what college you went to! <br> 

        After college moving away is hard. All your close friends and fellow students could miles away <br>
        and it would be hard to find someone who went to the same college. Well, were here to help!

        We are still under development but please check back soon!

        -College Dates
    </p>
    <button onclick="runcode()"Click here if you want to date someone who went to the same college!></button>

</body>

</html>
theme: jekyll-theme-midnight
